version: '3'
services:
  nome-projeto-aqui:
    build: '.'
    image: 'nginx:alpine'
    ports:
      - '8092:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./dist:/usr/share/nginx/html/
    restart: 'always'
    networks:
      default:
        ipv4_address: 10.253.254.110
networks:
  default:
   external:
     name: php-apache